version: "3"
services:
  db:
    container_name: chatbot-postgresql-dev
    image: "pgvector/pgvector:pg15"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chatbot-postgresql-dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
