"""add system prompt to chatbot

Revision ID: c12d72bd6655
Revises: e3e308ead997
Create Date: 2024-02-25 09:21:20.240627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12d72bd6655'
down_revision: Union[str, None] = 'e3e308ead997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot', sa.Column('system_prompt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot', 'system_prompt')
    # ### end Alembic commands ###
