"""initial migration

Revision ID: e3e308ead997
Revises: 
Create Date: 2024-02-20 13:35:43.731485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e308ead997'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('chatbot',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('vector_chunk_size', sa.Integer(), nullable=True),
    sa.Column('vector_chunk_overlap', sa.Integer(), nullable=True),
    sa.Column('vector_separators', sa.String(), nullable=True),
    sa.Column('vector_product_description_html_class', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_vector_scrape_url',
    sa.Column('chatbot_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_vector_scrape_url')
    op.drop_table('chatbot')
    op.drop_table('customer')
    # ### end Alembic commands ###
